### Login
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "elias.mraz84@hotmail.com",
  "password": "Password@123#"
}

### GET all comments
GET https://product-feedback-g3su.onrender.com/api-v1/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhhZjgxN2JlLTdhZWQtNDAxOC05MWQxLWMxNTUzOTBiYmJhNyIsImVtYWlsIjoiZWxpYXMubXJhejg0QGhvdG1haWwuY29tIiwiaWF0IjoxNzYyODY3NDI3fQ.k9oYsOTupmgRKN3cynQgbJPa7MZ1Fj4yxNIJUlDXki4
Content-Type: application/json

### GET a product by ID
GET http://localhost:3000/api-v1/comments/12eea6c6-c921-4ee1-b531-c99dd1ffe241
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhhZjgxN2JlLTdhZWQtNDAxOC05MWQxLWMxNTUzOTBiYmJhNyIsImVtYWlsIjoiZWxpYXMubXJhejg0QGhvdG1haWwuY29tIiwiaWF0IjoxNzYyODY3NDI3fQ.k9oYsOTupmgRKN3cynQgbJPa7MZ1Fj4yxNIJUlDXki4
Content-Type: application/json

### Create a new comment
POST http://localhost:3000/api-v1/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhhZjgxN2JlLTdhZWQtNDAxOC05MWQxLWMxNTUzOTBiYmJhNyIsImVtYWlsIjoiZWxpYXMubXJhejg0QGhvdG1haWwuY29tIiwiaWF0IjoxNzYyODY3NDI3fQ.k9oYsOTupmgRKN3cynQgbJPa7MZ1Fj4yxNIJUlDXki4
Content-Type: application/json

{
  "productId": "ce1575d9-85d4-409e-b586-da27dd41f1d1",
  "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
}

### Update a comment
PUT http://localhost:3000/api-v1/comments/b6154d9c-78de-4ef4-86d0-6fb43969294e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhhZjgxN2JlLTdhZWQtNDAxOC05MWQxLWMxNTUzOTBiYmJhNyIsImVtYWlsIjoiZWxpYXMubXJhejg0QGhvdG1haWwuY29tIiwiaWF0IjoxNzYyODY3NDI3fQ.k9oYsOTupmgRKN3cynQgbJPa7MZ1Fj4yxNIJUlDXki4
Content-Type: application/json

{
  "content": "Updated comment content goes here again."
}

### Delete a comment
DELETE http://localhost:3000/api-v1/comments/b6154d9c-78de-4ef4-86d0-6fb43969294e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhhZjgxN2JlLTdhZWQtNDAxOC05MWQxLWMxNTUzOTBiYmJhNyIsImVtYWlsIjoiZWxpYXMubXJhejg0QGhvdG1haWwuY29tIiwiaWF0IjoxNzYyODY3NDI3fQ.k9oYsOTupmgRKN3cynQgbJPa7MZ1Fj4yxNIJUlDXki4
Content-Type: application/json